#\u6570\u636E\u6E90\u914D\u7F6E
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://192.168.2.35:3306/mergeTest?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
spring.datasource.url=jdbc:mysql://121.89.242.0:43306/lims_ding?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true
spring.datasource.username=lims
spring.datasource.password=hntrilims
#spring.datasource.username=root
#spring.datasource.password=111111

#spring.datasource.initialSize=20
#spring.datasource.minIdle=50
#spring.datasource.maxActive=500

# BANNER
spring.banner.charset=UTF-8
spring.banner.location=classpath:banner.txt 
spring.banner.image.location=classpath:banner.gif
spring.banner.image.width=76 
spring.banner.image.height=
spring.banner.image.margin=2 
spring.banner.image.invert=false 

#\u670D\u52A1\u7AEF\u53E3\u914D\u7F6E
http.port=48888
server.port=8080
server.servlet.context-path=/lims
# \u5F00\u542Fhttps,\u914D\u7F6E\u8DDF\u8BC1\u4E66\u5BF9\u5E94
server.ssl.enabled=true
server.ssl.key-store=classpath:tomcat.keystore
# server.ssl.key-store-type=JKS
server.ssl.key-store-type=JKS
# \u5BC6\u7801
server.ssl.key-store-password=111111
# \u522B\u540D
server.ssl.key-alias=tomcat

#mybatis plus
#mapper\u6587\u4EF6\u626B\u63CF\u8DEF\u5F84\u914D\u7F6E
mybatis-plus.mapper-locations=classpath:mapper/*.xml
#\u5B9E\u4F53bean\u5305\u626B\u63CF
mybatis-plus.type-aliases-package=com.stu.manage.demo.entity
#log4j2\u914D\u7F6E
logging.config=classpath:log4j2.xml
#sql\u8F93\u51FA\u65E5\u5FD7\u7EA7\u522B
logging.level.com.stu.manage.demo.mapper = debug
spring.resources.static-locations=classpath:/templates/,classpath:/static/

#redis\u76F8\u5173\u914D\u7F6E
spring.redis.host=192.168.2.35
spring.redis.port=6379
#spring.redis.password=redis
#\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
spring.redis.timeout=10000ms
# \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09 \u9ED8\u8BA4 8
#spring.redis.lettuce.pool.max-active=16
# \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5 \u9ED8\u8BA4 8
#spring.redis.lettuce.pool.max-idle=8
# \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4,\u5355\u4F4D\u6BEB\u79D2\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09 \u9ED8\u8BA4 -1
#spring.redis.lettuce.pool.max-wait=1000ms
# \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5 \u9ED8\u8BA4 0
#spring.redis.lettuce.pool.min-idle=0

#\u9489\u9489H5\u5FAE\u5E94\u7528\u63A5\u5165
dingtalk.app_key=dingsniqlhiwk76cvbfb
dingtalk.app_secret=pcBaHyNbCpBrEZt7VgpRT065b46VghRVT36y_Xl53snf-3oKR2Y9gw0vA4wvvgF8
dingtalk.agent_id=1303982312
dingtalk.corp_id=ding6f801dee04343f9cbc961a6cb783455b
dingtalk.api_token=09a55a3d7d61392ca5d1b8693461db4e

dingtalk.token_url=https://oapi.dingtalk.com/gettoken
dingtalk.user_url=https://oapi.dingtalk.com/user/getuserinfo
dingtalk.info_url=https://oapi.dingtalk.com/topapi/v2/user/get
dingtalk.dept_url=https://oapi.dingtalk.com/department/get
#\u9489\u9489\u4F01\u4E1A\u5E94\u7528\u63A5\u53E3
ding_tushu_url=https://route.showapi.com/1626-1
ding_showapi_appid=740854
ding_showapi_sign=5005fe06612c4e419d73a1e3e6d0c3f1

#JWT\u5168\u5C40\u914D\u7F6E
# \u52A0\u5BC6\u79D8\u94A5
jwt.secret: dfjlaer********
# token\u6709\u6548\u65F6\u957F\uFF0C24\u5C0F\u65F6\uFF0C\u5355\u4F4D\u79D2
jwt.expire: 86400
jwt.header: token

#\u4E0B\u8F7D\u62A5\u544A\u8DEF\u5F84
report.path=/home/lims/doc/\u6211\u7684\u6587\u6863/lims/\u68C0\u9A8C\u62A5\u544A/
#report.path=D:\\\u62A5\u544A\\

#发票识别
orc.client.id=qkwiv4DyU7RGE74cH2G2TGUC
orc.client.secret=6kMFZ1cqvMD4tNw2kk8l5G1mzA6eIUyU
orc.auth.host=https://aip.baidubce.com/oauth/2.0/token?
orc.invoice.url=https://aip.baidubce.com/rest/2.0/ocr/v1/vat_invoice?access_token=
orc.invoice.verification.url=https://aip.baidubce.com/rest/2.0/ocr/v1/vat_invoice_verification
#表格
orc.from.url=https://aip.baidubce.com/rest/2.0/ocr/v1/accurate?access_token=



