#数据源配置
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:mysql://39.98.85.26:43306/lims?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true&allowMultiQueries=true
#spring.datasource.username=root
#spring.datasource.password=root@1234

spring.datasource.url=jdbc:mysql://39.103.131.122:43306/ERP_69?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=hntri123456
#本地环境
#spring.datasource.url=jdbc:mysql://192.168.2.202:43306/test_merge_team?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true&allowMultiQueries=true
#spring.datasource.username=root
#spring.datasource.password=123456


spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.connection-init-sql=50
spring.datasource.hikari.minimum-idle=50
spring.datasource.hikari.maximum-pool-size=300
# BANNER
spring.banner.charset=UTF-8
spring.banner.location=classpath:banner.txt
spring.banner.image.location=classpath:banner.gif
spring.banner.image.width=76
spring.banner.image.height=
spring.banner.image.margin=2
spring.banner.image.invert=false
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

#服务端口配置
server.servlet.context-path=/jkyErp
http.port=8081
server.port=48999
server.tomcat.max-swallow-size=2MB
#server.servlet.context-path=/lims
#开启https,配置跟证书对应
server.ssl.enabled=true
server.ssl.key-store=classpath:tomcat.keystore
# server.ssl.key-store-type=JKS
server.ssl.key-store-type=JKS
#密码
server.ssl.key-store-password=111111
#别名
server.ssl.key-alias=tomcat

# 内置Tomcat配置
server.tomcat.uri-encoding=UTF-8
##最小线程数
server.tomcat.min-spare-threads=500
##最大线程数
server.tomcat.max-threads=2500
##最大链接数
server.tomcat.max-connections=6500
##最大等待队列长度
server.tomcat.accept-count=1000
##请求头最大长度kb
server.max-http-header-size=1048576
##请请求体最大长度kb
server.tomcat.max-http-post-size=2097152
##链接建立超时时间
server.tomcat.connection-timeout=12000

#mybatis plus
#mapper文件扫描路径配置
mybatis-plus.mapper-locations=classpath:mapper/*.xml
#实体bean包扫描
mybatis-plus.type-aliases-package=com.lims.manage.demo.entity
#sql输出日志级别
logging.level.com.lims.manage.erp.* = debug
#logging.file=D:\\doc\\erp.log
spring.resources.static-locations=classpath:/templates/,classpath:/static/
#redis开发环境公网相关配置
spring.redis.host=121.89.242.0
spring.redis.port=46379
#内网
#spring.redis.host=192.168.2.202
#spring.redis.port=46379
spring.redis.password=hntri@2021_12_21
#redis超时时间
spring.redis.timeout=30000
#连接池最大连接数（使用负值表示没有限制） 默认 8
spring.redis.lettuce.pool.max-active=16
#连接池中的最大空闲连接 默认 8ActivitiController.java
spring.redis.lettuce.pool.max-idle=8
#连接池最大阻塞等待时间,单位毫秒（使用负值表示没有限制） 默认 -1
spring.redis.lettuce.pool.max-wait=10000ms
#连接池默认最小链接数 0
#spring.redis.lettuce.pool.min-idle=0

#minio开发环境公网配置文件
minio.ip=http://121.89.242.0
minio.port=9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
#钉钉相关配置
#内部应用
dingtalk.app_key=dinguvlcwkolkjbykfvz
dingtalk.app_secret=o6En3k76CofqF7KQC08zW-31GMTNFVKskk_jSCvT3Vxws8S7bxFYfT5Uw7AopHGl
#token
dingtalk.token_url=https://oapi.dingtalk.com/gettoken
#用户信息
dingtalk.user_url=https://oapi.dingtalk.com/user/listbypage
#获取组织架构
dingtalk.dept_url=https://oapi.dingtalk.com/department/list

#契约所相关配置
#AppToken
qiyuesuo.AppToken=vsBA6Xumb5
#token加密秘钥（加密方式MD5）Md5(appToken+appSercert+timestamp+nonce)
#timestamp当前系统时间不允许偏差超过15分钟、nonce取值UUID
qiyuesuo.AppSecret=sBPyfN3XwqLRWqMTyQ4gpQmVdAz88L
#api接口调用地址
qiyuesuo.Url=http://dzqz.hntri.com:9182
#根据文件类型创建合同文档
qiyuesuo.Create=/v2/document/createbyfile
#创建合同
qiyuesuo.Add=/contract/createbycategory
#发起合同
qiyuesuo.Send=/contract/send
#合同签署页面
qiyuesuo.Sign=/contract/signurl
#删除合同
qiyuesuo.Delete=/contract/delete
#印章列表
qiyuesuo.List=/seal/list
#文件下载
qiyuesuo.Download=/contract/download
#部门列表
qiyuesuo.dept=/company/list
#用印流程标识
qiyuesuo.categoryId=2934717410113839636
#linux临时文件路径
autograph.path=/usr/local/
#样品扫码小程序配置代理域名地址
qrcode.url=https://hntri.hkgglclc.com/home/JkyErp/sp?id=
#windows本地临时文件路径
#autograph.path=D:\\doc\\saveOriginalRecord\\
#pageOffice
posyspath=/home/PageOfficeLic
popassword=111111
qrcode=https://39.103.131.122:48998/jkyErp/index.html#/reportValidation?reportCode=
#logoUrl
logoUrl=http://121.89.242.0:9000/active-img/logo.jpg
