adminIsValid=true
production=false
location=/home/lims/apache-tomcat-7.0.73/webapps/lims/file/
isValidIP=47.92.36.159
#document=/home/lims/doc/
#template=/home/lims/apache-tomcat-7.0.73/webapps/lims/file/check/
#down=/home/lims/apache-tomcat-7.0.73/webapps/lims/file/down/
#accessory=/home/lims/apache-tomcat-7.0.73/webapps/lims/file/accessory/
#libreoffice=/opt/libreoffice5.2/program
oldLocation=/home/lims/apache-tomcat-7.0.73/webapps/lims/file/
libreoffice=C:\\Program Files\\LibreOffice 5\\program
minSumCheckCost=20000
minNumber=6
